# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programas Py\Informatica 2\Proyecto final\proyecto-final\Version_mario_proyecto_final\interfaz_moderna.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(901, 650)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(450, 0, 571, 671))
        self.widget.setStyleSheet("QWidget {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #0077b6, stop:0.5 #0096c7, stop:1 #00b4d8);\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: transparent;  /* Fondo transparente para QLabel */\n"
"    color: white;  /* Color del texto del QLabel */\n"
"    font-size: 16px;  /* Tamaño de fuente del QLabel */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;  /* Fondo sólido blanco para QLineEdit */\n"
"    border: 2px solid #00b4d8;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #0077b6; /* Color del borde al enfocar */\n"
"    outline: none;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(0, 119, 182)\n"
"}")
        self.widget.setObjectName("widget")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(-10, 0, 16, 661))
        self.widget_3.setStyleSheet("QWidget {\n"
"    background-color: rgb(0, 180, 216);\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 131, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(410, 10, 21, 21))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/prefijoNuevo/Img_Moca/Moca2.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(220, 10, 191, 20))
        self.label_4.setObjectName("label_4")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(-40, -20, 501, 691))
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: rgb(225, 255, 255);\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(0, 119, 182);\n"
"}\n"
"\n"
"QPushButton{\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(0, 119, 182)\n"
"}\n"
"QLineEdit {\n"
"    background-color: rgb(0, 119, 182); /* Fondo sólido blanco para QLineEdit */\n"
"    border: 2px solid #00b4d8;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    color: white;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(70, 40, 131, 41))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(440, 620, 41, 41))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/prefijoNuevo/Img_Moca/Alzcare.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">OPCIONES</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:8pt;\">Test Moca - Deterioro cognitivo</span></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">ENUNCIADO</span></p></body></html>"))
import recursos_interfazmoca_rc
