# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programas Py\Informatica 2\Proyecto final\varios Alzcare\interfaz_registro1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(901, 612)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 471, 651))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(225, 255, 255);\n"
"}\n"
"\n"
"QLabel{\n"
"    color:white;\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(130, 230, 191, 191))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Programas Py\\Informatica 2\\Proyecto final\\varios Alzcare\\Alzcare.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(450, 0, 471, 621))
        self.widget_2.setStyleSheet("QWidget {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #0077b6, stop:0.5 #0096c7, stop:1 #00b4d8);\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: transparent;  /* Fondo transparente para QLabel */\n"
"    color: white;  /* Color del texto del QLabel */\n"
"    font-size: 16px;  /* Tamaño de fuente del QLabel */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;  /* Fondo sólido blanco para QLineEdit */\n"
"    border: 2px solid #00b4d8;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #0077b6; /* Color del borde al enfocar */\n"
"    outline: none;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(0, 180, 216);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(-10, 0, 16, 641))
        self.widget_3.setStyleSheet("QWidget {\n"
"    background-color: rgb(0, 180, 216);\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(30, 40, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_regresar = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_regresar.setGeometry(QtCore.QRect(90, 560, 93, 28))
        self.pushButton_regresar.setObjectName("pushButton_regresar")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(30, 230, 171, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/prefijoNuevo/Img_interfaz2/paciente.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(240, 250, 171, 171))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/prefijoNuevo/Img_interfaz2/cuidador.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_salir = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_salir.setGeometry(QtCore.QRect(250, 560, 93, 28))
        self.pushButton_salir.setObjectName("pushButton_salir")
        self.pushButton_paciente = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_paciente.setGeometry(QtCore.QRect(70, 230, 93, 28))
        self.pushButton_paciente.setStyleSheet("QPusButton{\n"
"    background-color: rgb(225, 255, 255);\n"
"}")
        self.pushButton_paciente.setObjectName("pushButton_paciente")
        self.pushButton_cuidador = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_cuidador.setGeometry(QtCore.QRect(280, 230, 93, 28))
        self.pushButton_cuidador.setObjectName("pushButton_cuidador")

        self.retranslateUi(Form)
        self.pushButton_salir.clicked['bool'].connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p>Bienvenido a Alzcare, por favor seleccione</p><p>el tipo de usuario a registrar</p></body></html>"))
        self.pushButton_regresar.setText(_translate("Form", "Regresar"))
        self.pushButton_salir.setText(_translate("Form", "Salir"))
        self.pushButton_paciente.setText(_translate("Form", "Paciente"))
        self.pushButton_cuidador.setText(_translate("Form", "Cuidador"))
import recursos_rc
